####################
# Account settings #
####################
${USE_AWS}AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
${USE_AWS}AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

###################
# Backup settings #
###################
${USE_AWS_BACKUP}BACKUP_AWS_STORAGE_BUCKET_NAME=${AWS_BACKUP_BUCKET_NAME}
#Backups files deletion is handled by bucket rules when True
${USE_AWS_BACKUP}AWS_BACKUP_BUCKET_DELETION_RULE_ENABLED=${AWS_BACKUP_BUCKET_DELETION_RULE_ENABLED}
${USE_AWS_BACKUP}AWS_BACKUP_YEARLY_RETENTION=${AWS_BACKUP_YEARLY_RETENTION}
${USE_AWS_BACKUP}AWS_BACKUP_MONTHLY_RETENTION=${AWS_BACKUP_MONTHLY_RETENTION}
${USE_AWS_BACKUP}AWS_BACKUP_WEEKLY_RETENTION=${AWS_BACKUP_WEEKLY_RETENTION}
${USE_AWS_BACKUP}AWS_BACKUP_DAILY_RETENTION=${AWS_BACKUP_DAILY_RETENTION}
