POSTGRES_DB=${SUPPORT_DB_NAME}
POSTGRES_USER=${SUPPORT_DB_USER}
POSTGRES_PASSWORD=${SUPPORT_DB_PASSWORD}

SUPPORT_DB_SERVER=${SUPPORT_DB_SERVER}
SUPPORT_DB_NAME=${SUPPORT_DB_NAME}
SUPPORT_DB_USER=${SUPPORT_DB_USER}
SUPPORT_DB_PASSWORD=${SUPPORT_DB_PASSWORD}
SUPPORT_DB_PORT=${SUPPORT_DB_PORT}
SUPPORT_DB_INTERNAL_PORT=${SUPPORT_DB_INTERNAL_PORT}
SUPPORT_DB_INTERNAL_SERVER=${SUPPORT_DB_INTERNAL_SERVER}

KOBO_DB_SERVER=${KOBO_DB_SERVER}
KOBO_DB_PORT=${KOBO_DB_PORT}
KOBO_DB_NAME=${KOBO_DB_NAME}
KOBO_CAT_DB_NAME=${KOBO_CAT_DB_NAME}
KOBO_DB_USER=${KOBO_DB_USER}
KOBO_DB_PASSWORD=${KOBO_DB_PASSWORD}

KOBO_API_URI=${KOBO_API_URI}